services:
  - type: web
    name: telegram-order-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    runtime: python
    pythonVersion: 3.11
